# Generated by Django 5.0.7 on 2024-07-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudDetail',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('roll', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('sclass', models.IntegerField()),
                ('saddress', models.CharField(max_length=100)),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('socialscience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('sclass', models.IntegerField()),
                ('saddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('socialscience', models.IntegerField()),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='cxlApp.studentdetail')),
            ],
        ),
    ]
